name: Cache 101

on: 
  push:
    branches: ["master"]
    
  pull_request:
    branches: ["master"]
    

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
 
      - name: Pythion setup with cache.
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
          
      - name: Install pip dependencies
        run: pip install -r requirements.txt
    
